import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LeftSideBar from "@/components/layout/LeftSideBar";
import SideBar from "@/components/layout/SideBar";
import { Button } from "../components/ui/button";
import TopBar from "@/components/layout/TopBar";
import { Header } from "@/components/layout/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'${inter.className} flex items-start justify-between'}>  
     
          <SideBar/>          
          <main className="grid w-full h-50 pl-[200px]">
          <Header/>
          {children}       
          </main>       
      </body>
    </html>
  );
}
